---
title: "SL_lab_unsupervised"
author: "David Tsai"
date: "3/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Principal Components
```{r}
dimnames(USArrests)
apply(USArrests, 2, mean)
apply(USArrests, 2, var)
```


Standardize the variables
```{r}
pca.out = prcomp(USArrests, scale = T)
pca.out
names(pca.out)
biplot(pca.out, cex = .5, scale = 0)
```


### K-Means Clustering
Make some data with clusters.
```{r}
set.seed(101)
x = matrix(rnorm(100 *2), 100, 2)
xmean = matrix(rnorm(8, sd = 4), 4, 2)
which = sample(1:4, 100, replace = T)
x = x + xmean[which,]

plot(x, col = which, pch = 20)
```

'kmeans' algorithm
```{r}
km.out = kmeans(x, 4, nstart = 15)
km.out

plot(x, col = km.out$cluster, cex = 2, pch = 1, lwd = 2)
points(x, col = c(4, 3, 2, 1)[which], pch = 19)
```

### Hierarchical Clustering
```{r}
hc.complete = hclust(dist(x), method = "complete")
plot(hc.complete, main = "cluster dendrogram - complete")

hc.single = hclust(dist(x), method = "single")
plot(hc.single, main = "cluster dendrogram - single")

hc.average = hclust(dist(x), method = "average")
plot(hc.average, main = "cluster dendrogram - average")
```

```{r}
hc.cut = cutree(hc.complete, 4)
table(hc.cut, which)
table(hc.cut, km.out$cluster)
```


```{r}
plot(hc.complete, labels = which)
```
